[project]
name = "backtester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "ta-lib>=0.4.0",
    "ccxt>=4.0.0",
    "typer>=0.9.0",
    "rich>=13.0.0"
]
